# .scrutinizer.yml
checks:
  php: true
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  environment:
    php:
      version: 8.0
      pecl_extensions:
        - mbbinary
  tests:
    override:
      -
        command: 'composer run test-coverage'
        coverage:
          file: 'coverage.xml'
          format: 'clover'
filter:
  excluded_paths:
    - "tests/"